#!/bin/bash

# Run clang-tidy on all C++ source files in the project
# Requires compile_commands.json (generated by cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON)
# Exits with error code 1 if any warnings are found

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "Running clang-tidy on SuperKMeans project..."
echo "Project root: $PROJECT_ROOT"

if ! command -v clang-tidy &> /dev/null; then
    echo "Error: clang-tidy not found. Please install it first."
    exit 1
fi

# Check for compile_commands.json
COMPILE_DB="$PROJECT_ROOT/compile_commands.json"
if [ ! -f "$COMPILE_DB" ]; then
    echo "Error: compile_commands.json not found."
    echo "Generate it with: cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
    exit 1
fi

DIRECTORIES=(
    "tests"
    "examples"
    "python"
)

EXTENSIONS=("cpp")

total_files=0
files_with_warnings=0

for dir in "${DIRECTORIES[@]}"; do
    dir_path="$PROJECT_ROOT/$dir"

    if [ ! -d "$dir_path" ]; then
        echo "Warning: Directory $dir does not exist, skipping..."
        continue
    fi

    echo "Checking directory: $dir"

    for ext in "${EXTENSIONS[@]}"; do
        while IFS= read -r -d '' file; do
            total_files=$((total_files + 1))
            relative_file="${file#$PROJECT_ROOT/}"

            # Only check warnings from headers in include/superkmeans/
            if ! clang-tidy -p "$PROJECT_ROOT" "$file" 2>&1 | grep "warning:" | grep -q "include/superkmeans/"; then
                echo "  ✓ $relative_file"
            else
                echo "  ✗ $relative_file"
                clang-tidy -p "$PROJECT_ROOT" "$file" 2>&1 | grep "warning:" | grep "include/superkmeans/" | head -10
                files_with_warnings=$((files_with_warnings + 1))
            fi
        done < <(find "$dir_path" -type f -name "*.$ext" -not -name "generate_*" -print0)
    done
done

echo ""
echo "Checked $total_files file(s)."

if [ "$files_with_warnings" -eq 0 ]; then
    echo "✓ No clang-tidy warnings found!"
    exit 0
else
    echo "✗ Found warnings in $files_with_warnings file(s)."
    exit 1
fi
